# name: Deploy Vite React App

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout repository
#       uses: actions/checkout@v2

#     - name: Set up Node.js
#       uses: actions/setup-node@v2
#       with:
#         node-version: '18'

#     - name: Install dependencies
#       run: npm install

#     - name: Build Vite React app
#       run: npm run build

#     - name: Copy dist folder to server
#       env:
#         SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
#       run: |
#         sudo apt-get install -y sshpass
#         sshpass -p $SSH_PASSWORD scp -o StrictHostKeyChecking=no -r dist/ ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:${{ secrets.SSH_DESTINATION }}

#     - name: Restart PM2 process
#       env:
#         SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
#       run: |
#         sshpass -p $SSH_PASSWORD ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} 'pm2 restart dashboard'
